.deploy: &deploy
  stage: deploy
  only:
    - master
    - main
  script: |
    eval $(ssh-agent)
    ssh-add ~/.ssh/dnull_shellshock_private_key.ssh
    echo "${PROJECT_PATH}"
    cd "${HOME}/${PROJECT_PATH}"
    git pull --rebase origin main
  tags: []

stages:
  - deploy

bfg:deploy:
  <<: *deploy
  tags:
    - bfg

sirius:deploy:
  <<: *deploy
  tags:
    - sirius

pi:deploy:
  <<: *deploy
  tags:
    - pi
