services:
  traefik:
    image: traefik:v1.7
    labels:
      - traefik.frontend.rule=Host:traefik.example.com
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.auth.basic.users=admin:passheresha/
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
version: '3'
